apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-01
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /Users/sigreen/Public
    server: 192.168.64.1
    readOnly: false